name: pythia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip
  - pip:
    - tensorflow==2.1.0
    - tensorflow-addons==0.9.1
    - pandas==1.0.1
    - numpy==1.18.1
    - h5py==2.10.0

